#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 18 15:24:27 2018

@author: sakurai
"""

import chainercv


class ChainerSSD300(object):
    def __init__(self):
        self.net = chainercv.links.model.ssd.SSD300(pretrained_model='voc0712')

    def predict(image_hwc_rgb):
        chw_rgb = image_hwc_rgb.transpose(2, 0, 1)
        bboxes, labels, scores = self.net.predict([chw_rgb])
        bboxes, labels, scores = bboxes[0], labels[0], scores[0]
        return bboxes, labels, scores

if __name__ == '__main__':
